image: node:8

cache:
  paths:
  - node_modules/
  - scripts/

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_gitlab
    - chmod 700 ~/.ssh/id_rsa_gitlab
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa_gitlab
    - ssh-keyscan -H "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - echo "Deploy to dev server"
    - ssh root@217.182.193.137 "bash -s" < ./deploy.sh
  environment:
    name: dev
    url: https://dev-api.animemixedworld.net
  only:
  - master