export default {
  EVENTS: "Events",
  NOTES: "Notes",
  POSTS: "Posts",
  POST_IMAGES: "Post_Images",
  POST_VIDEOS: "Post_Videos",
  POST_ACTION: "Post_Action",
  ALBUMS: "Albums",
  COMMENTS: "Comments",
  COMMENT_IMAGES: "Comment_Images",
  LIKES: "Likes",
  SHARES: "Shares",
  HISTORY: "History",
  USERS_PROFILE: "Users_Profile",
  USERS: "Users",
  ADVERTS: "Adverts",
  CHARACTER_PROFILE: "Character_Profile",
  CHARACTER_ABILITIES: "Character_Abilities",
  CHARACTER_EQUIPMENT: "Character_Equipment",
  CHARACTER_STATS: "Character_Stats",
};
