export default {
  Socket: {
    // EVENTS
    API_REQUEST_EVENTS: "@API/REQUEST_EVENTS",
    API_RESPONSE_EVENTS: "@API/RESPONSE_EVENTS",
    API_FAILED_EVENTS: "@API/FAILED_EVENTS",

    // NOTES
    API_REQUEST_NOTES: "@API/REQUEST_NOTES",
    API_RESPONSE_NOTES: "@API/RESPONSE_NOTES",
    API_FAILED_NOTES: "@API/FAILED_NOTES",

    // POSTS
    API_REQUEST_POSTS: "@API/REQUEST_POSTS",
    API_RESPONSE_POSTS: "@API/RESPONSE_POSTS",
    API_FAILED_POSTS: "@API/FAILED_POSTS",

    // POST
    API_REQUEST_POST: "@API/REQUEST_POST",
    API_RESPONSE_POST: "@API/RESPONSE_POST",
    API_FAILED_POST: "@API/FAILED_POST",

    // LIKE
    API_REQUEST_LIKES: "@API/REQUEST_LIKES",
    API_RESPONSE_LIKES: "@API/RESPONSE_LIKES",
    API_FAILED_LIKES: "@API/FAILED_LIKES",

    // ADD LIKE
    API_REQUEST_ADD_LIKE: "@API/REQUEST_ADD_LIKE",
    API_RESPONSE_ADD_LIKE: "@API/RESPONSE_ADD_LIKE",
    API_FAILED_ADD_LIKE: "@API/FAILED_ADD_LIKE",

    // DELETE LIKE
    API_REQUEST_DELETE_LIKE: "@API/REQUEST_DELETE_LIKE",
    API_RESPONSE_DELETE_LIKE: "@API/RESPONSE_DELETE_LIKE",
    API_FAILED_DELETE_LIKE: "@API/FAILED_DELETE_LIKE",

    // COMMENT
    API_REQUEST_COMMENTS: "@API/REQUEST_COMMENTS",
    API_RESPONSE_COMMENTS: "@API/RESPONSE_COMMENTS",
    API_FAILED_COMMENTS: "@API/FAILED_COMMENTS",

    // ADD COMMENT
    API_REQUEST_ADD_COMMENT: "@API/REQUEST_ADD_COMMENT",
    API_RESPONSE_ADD_COMMENT: "@API/RESPONSE_ADD_COMMENT",
    API_FAILED_ADD_COMMENT: "@API/FAILED_ADD_COMMENT",

    // DELETE COMMENT
    API_REQUEST_DELETE_COMMENT: "@API/REQUEST_DELETE_COMMENT",
    API_RESPONSE_DELETE_COMMENT: "@API/RESPONSE_DELETE_COMMENT",
    API_FAILED_DELETE_COMMENT: "@API/FAILED_DELETE_COMMENT",

    // PROFILE BY ID
    API_REQUEST_PROFILE_BY_ID: "@API/REQUEST_PROFILE_BY_ID",
    API_RESPONSE_PROFILE_BY_ID: "@API/RESPONSE_PROFILE_BY_ID",
    API_FAILED_PROFILE_BY_ID: "@API/FAILED_PROFILE_BY_ID",

    // CURRENT USER BY ID
    API_REQUEST_CURRENT_USER_BY_ID: "@API/REQUEST_CURRENT_USER_BY_ID",
    API_RESPONSE_CURRENT_USER_BY_ID: "@API/RESPONSE_CURRENT_USER_BY_ID",
    API_FAILED_CURRENT_USER_BY_ID: "@API/FAILED_CURRENT_USER_BY_ID",

    // NEW SOCKET ID
    API_REQUEST_NEW_SOCKET_ID: "@API/REQUEST_NEW_SOCKET_ID",
    API_RESPONSE_NEW_SOCKET_ID: "@API/RESPONSE_NEW_SOCKET_ID",
    API_FAILED_NEW_SOCKET_ID: "@API/FAILED_NEW_SOCKET_ID",

    // ADD CLIENT WITH SOCKET ID
    API_REQUEST_ADD_CLIENT: "@API/REQUEST_ADD_CLIENT",
    API_RESPONSE_ADD_CLIENT: "@API/RESPONSE_ADD_CLIENT",
    API_FAILED_ADD_CLIENT: "@API/FAILED_ADD_CLIENT",

    // OPEN MESSAGE
    API_REQUEST_OPEN_MESSAGE: "@API/REQUEST_OPEN_MESSAGE",
    API_RESPONSE_OPEN_MESSAGE: "@API/RESPONSE_OPEN_MESSAGE",
    API_FAILED_OPEN_MESSAGE: "@API/FAILED_OPEN_MESSAGE",

    // UPLOAD
    API_RESPONSE_UPLOAD_FILES: "@API/RESPONSE_UPLOAD_FILES",
    API_FAILED_UPLOAD_FILES: "@API/FAILED_UPLOAD_FILES",

    // DELETE_FILE
    API_REQUEST_DELETE_FILES: "@API/REQUEST_DELETE_FILES",
    API_RESPONSE_DELETE_FILES: "@API/RESPONSE_DELETE_FILES",
    API_FAILED_DELETE_FILES: "@API/FAILED_DELETE_FILES"
  }
};
